name: Pull Request Validation
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened]
permissions:
  pull-requests: write
  
jobs:
  add-label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Add label to pull request
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'bug, enhancement, help wanted'
      - name: Label when approved
        if: github.event.review.state == 'approved'
        uses: ableco/label-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
  assign-creator:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Assign PR creator
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const creator = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;

            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              assignees: [creator]
            });

